Blog_platform/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('posts.urls')),
    path('account/', include('users.urls')),
    path('analytics/', include('analytics.urls')),
    path('api/', include('api.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

api/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('posts/', views.PostList.as_view(), name='api_post_list'),
    path('posts/<int:pk>/', views.PostDetails.as_view(), name='api_post_details'),
    path('categories/', views.CategoryList.as_view(), name='api_categories_list'),
    path('categories/<int:pk>/', views.CategoryDetails.as_view(), name='api_categories_details'),
    path('comments/', views.CommentList.as_view(), name='api_comments_list'),
    path('comments/<int:pk>/', views.CommentDetails.as_view(), name='api_comments_details'),
    path('comment_reactions/', views.CommentReactionList.as_view(), name='api_comment_reactions_list'),
    path('comment_reactions/<int:pk>/', views.CommentReactionDetails.as_view(), name='api_comment_reactions_details'),

    path('login/', views.LoginView.as_view(), name='api_login'),
    path('users/', views.UserList.as_view(), name='api_users_list'),
    path('users/<int:pk>/', views.UserDetails.as_view(), name='api_users_details'),
    path('email_subscribers/', views.EmailSubscriberList.as_view(), name='api_email_subscribers_list'),
    path('email_subscribers/<int:pk>/', views.EmailSubscriberDetails.as_view(), name='api_email_subscribers_details'),
    path('unban_requests/', views.UnbanRequestList.as_view(), name='api_unban_requests_list'),
    path('unban_requests/<int:pk>/', views.UnbanRequestDetails.as_view(), name='api_unban_requests_details'),
]

posts/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from . import views

urlpatterns = [
    path('', views.PostListView.as_view(), name='post_list'),
    path('post/<int:post_id>/add_comment/<int:comment_id>', views.CreateCommentView.as_view(),
         name='add_comment_reply'),
    path('post/<int:post_id>/add_comment', views.CreateCommentView.as_view(), name='add_comment'),
    path('post/<int:post_id>/edit', views.EditPostView.as_view(), name='edit_post'),
    path('post/<int:post_id>/delete', views.DeletePostView.as_view(), name='delete_post'),
    path('post/<int:post_id>/', views.PostDetailView.as_view(), name='post_detail'),
    path('post/share/', views.SharePostView.as_view(), name='share_post'),
    path('post/create/', views.CreatePostView.as_view(), name='create_post'),
    path('post/search/', views.SearchResultsView.as_view(), name='search_results'),
    path('category/<int:category_id>/', views.CategoryDetailView.as_view(), name='category_detail'),
    path('category/create/', views.CreateCategoryView.as_view(), name='category_create'),
    path('comment/<int:comment_id>/delete', views.DeleteCommentView.as_view(), name='comment_delete'),
    path('comment/<int:comment_id>/reaction', views.CommentReactionView.as_view(), name='comment_reaction')
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

posts/models.py
import logging

import bleach
from ckeditor.fields import RichTextField
from django.conf import settings
from django.db import models

logger = logging.getLogger(__name__.split('.')[0])


class Post(models.Model):
    title = models.CharField(max_length=100, unique=True)
    content = RichTextField()
    category = models.ForeignKey('Category', on_delete=models.SET_NULL, null=True)
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True)
    date_scheduled = models.DateTimeField(null=True, blank=True)
    date_published = models.DateTimeField(null=True, blank=True)
    views = models.PositiveIntegerField(default=0)
    share_count = models.IntegerField(default=0)
    is_published = models.BooleanField(default=False)

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        # Clean the content field with bleach using the settings from settings.py
        self.content = bleach.clean(
            self.content,
            tags=settings.ALLOWED_TAGS,
            attributes=settings.ALLOWED_ATTRIBUTES,
            protocols=settings.ALLOWED_PROTOCOLS,
            strip=settings.STRIP,
            strip_comments=settings.STRIP_COMMENTS,
        )
        super().save(*args, **kwargs)

    def delete(self, *args, **kwargs):
        logger.warning(f"Deleting post: {self.title} (ID: {self.pk})")
        super().delete(*args, **kwargs)

    class Meta:
        ordering = ['-date_published']


class Category(models.Model):
    title = models.CharField(max_length=30)
    description = models.TextField()

    def delete(self, *args, **kwargs):
        logger.warning(f"Deleting category: {self.title} (ID: {self.pk})")
        super().delete(*args, **kwargs)

    def __str__(self):
        return self.title

    class Meta:
        ordering = ['title']
        verbose_name_plural = 'Categories'


class Comment(models.Model):
    content = models.CharField(max_length=500)
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True)
    post = models.ForeignKey('Post', on_delete=models.CASCADE)
    timestamp = models.DateTimeField(auto_now_add=True)
    parent_comment = models.ForeignKey('self', on_delete=models.CASCADE, null=True, default=None)
    is_deleted = models.BooleanField(default=False)
    is_profane = models.BooleanField(default=False)
    is_negative = models.BooleanField(default=False)

    @property
    def likes_count(self):
        return self.reactions.filter(reaction_type='like').count()

    @property
    def dislikes_count(self):
        return self.reactions.filter(reaction_type='dislike').count()

    def delete(self, *args, **kwargs):
        logger.warning(f"Deleting comment: {self.content} (ID: {self.pk})")
        super().delete(*args, **kwargs)

    def __str__(self):
        return str(self.id)

    class Meta:
        ordering = ['timestamp']


class CommentReaction(models.Model):
    REACTION_CHOICES = [
        ('like', 'Like'),
        ('dislike', 'Dislike')
    ]

    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    comment = models.ForeignKey('Comment', related_name='reactions', on_delete=models.CASCADE)
    reaction_type = models.CharField(max_length=10, choices=REACTION_CHOICES)

    class Meta:
        unique_together = ['user', 'comment']

posts/views.py
import json
import logging
from datetime import timedelta

from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import PermissionDenied
from django.db import transaction
from django.db.models import F
from django.http import HttpResponseBadRequest, JsonResponse
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse, reverse_lazy
from django.utils import timezone
from django.views import View
from django.views.generic import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView

from analytics.models import ViewedPost
from .forms import PostForm, CategoryForm, CommentForm
from .models import Post, Category, Comment, CommentReaction

logger = logging.getLogger(__name__.split('.')[0])


class SearchResultsView(ListView):
    model = Post
    template_name = 'posts/search_results.html'
    context_object_name = 'search_results'
    paginate_by = 3

    def get_queryset(self):
        query = self.request.GET.get('query')
        if query:
            return Post.objects.filter(title__icontains=query)
        return Post.objects.none()


class PostListView(ListView):
    model = Post
    template_name = 'posts/post_list.html'
    context_object_name = 'posts'
    paginate_by = 3

    def get_queryset(self):
        return Post.objects.filter(is_published=True)

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['categories'] = Category.objects.all()
        return context


class PostDetailView(DetailView):
    model = Post
    template_name = 'posts/post_detail.html'
    context_object_name = 'post'

    def get_object(self, queryset=None):
        post_id = self.kwargs.get('post_id')
        return get_object_or_404(self.model, pk=post_id)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['comments'] = self.object.comment_set.filter(parent_comment__isnull=True).order_by(
            '-timestamp').prefetch_related('comment_set')
        context['form'] = CommentForm()
        return context

    def get(self, request, *args, **kwargs):
        response = super().get(request, *args, **kwargs)
        self.handle_views_counter()
        return response

    def handle_views_counter(self):
        # Check if the post was viewed from current IP in the last 24 hours
        ip = self.request.META.get('REMOTE_ADDR')
        time_threshold = timezone.now() - timedelta(hours=24)
        recent_views = ViewedPost.objects.filter(
            post=self.object, ip_address=ip, timestamp__gte=time_threshold
        )
        session_key = f'viewed_post_{self.object.id}'

        # Session-Based + IP-Based counting
        if not self.request.session.get(session_key) and not recent_views.exists():
            # Directly update 'views' in the database
            Post.objects.filter(pk=self.object.pk).update(views=F('views') + 1)

            # Update the session
            self.request.session[session_key] = True
            self.request.session.set_expiry(86400)  # 24 hours in seconds
            ViewedPost.objects.create(post=self.object, ip_address=ip)


class SharePostView(View):
    http_method_names = ['post']

    # noinspection PyMethodMayBeStatic
    def post(self, request, *args, **kwargs):
        post_id = json.loads(request.body).get('post_id')
        Post.objects.filter(pk=post_id).update(share_count=F('share_count') + 1)
        return JsonResponse({'success': True})


class CreatePostView(LoginRequiredMixin, CreateView):
    model = Post
    form_class = PostForm
    template_name = 'posts/post_create.html'

    def dispatch(self, request, *args, **kwargs):
        if not request.user.has_perm('posts.add_post'):
            messages.error(
                request, 'Only authorized authors are allowed to create posts. Contact support to become an author.'
            )
            return redirect('user_detail', request.user.id)
        return super().dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        post = form.save(commit=False)
        post.author = self.request.user
        response = super().form_valid(form)
        messages.success(self.request, 'Successfully published a new post')
        logger.info(f'User {self.request.user} created new post {post.pk}')
        return response

    def get_success_url(self):
        return reverse('user_detail', args=[self.request.user.id])


class EditPostView(LoginRequiredMixin, UpdateView):
    model = Post
    form_class = PostForm
    template_name = 'posts/post_edit.html'
    context_object_name = 'post'

    def get_success_url(self):
        return reverse('post_detail', args=[self.object.id])

    def get_object(self, queryset=None):
        obj = get_object_or_404(self.model, pk=self.kwargs.get('post_id'))
        if obj.author != self.request.user:
            raise PermissionDenied("You don't have permission to delete this post.")
        return obj

    def form_valid(self, form):
        response = super().form_valid(form)
        messages.success(self.request, 'Successfully updated post!')
        logger.info(f'User {self.request.user} edited post {self.object.pk}')
        return response


class DeletePostView(LoginRequiredMixin, DeleteView):
    model = Post
    http_method_names = ['post']

    def get_object(self, queryset=None):
        obj = get_object_or_404(self.model, pk=self.kwargs.get('post_id'))
        if obj.author != self.request.user:
            raise PermissionDenied("You don't have permission to delete this post.")
        return obj

    def form_valid(self, form):
        response = super().form_valid(form)
        messages.success(self.request, 'Successfully deleted post!')
        logger.warning(f'User {self.request.user} deleted post {self.object.pk}')
        return response

    def get_success_url(self):
        return reverse('user_detail', args=[self.request.user.id])


class CategoryDetailView(DetailView):
    model = Category
    template_name = 'posts/category_detail.html'
    context_object_name = 'category'

    def get_object(self, queryset=None):
        category_id = self.kwargs.get('category_id')
        return get_object_or_404(self.model, pk=category_id)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['posts'] = self.object.post_set.filter(is_published=True)
        return context


class CreateCategoryView(LoginRequiredMixin, CreateView):
    model = Category
    form_class = CategoryForm
    template_name = 'posts/category_create.html'

    def dispatch(self, request, *args, **kwargs):
        if not request.user.has_perm('posts.add_category'):
            messages.error(
                request, 'Only authorized authors are allowed to create categories.Contact support to become an author.'
            )
            return redirect('user_detail', request.user.id)
        return super().dispatch(request, *args, **kwargs)

    def get_success_url(self):
        next_url = self.request.GET.get('next', 'post_list')
        if next_url.startswith('/'):
            return next_url
        return reverse_lazy(next_url)

    def form_valid(self, form):
        category = form.save(commit=False)
        response = super().form_valid(form)
        messages.success(self.request, 'Successfully created a new category')
        logger.info(f'User {self.request.user} created new category {category.pk}')
        return response


class CreateCommentView(LoginRequiredMixin, CreateView):
    model = Comment
    form_class = CommentForm
    http_method_names = ['post']

    def get_success_url(self):
        post_id = self.kwargs['post_id']
        return reverse('post_detail', args=[post_id])

    def form_valid(self, form):
        comment = form.save(commit=False)
        comment.author = self.request.user
        comment.post = get_object_or_404(Post, pk=self.kwargs['post_id'])

        parent_comment_id = self.request.POST.get('reply_to_id')
        if parent_comment_id:
            comment.parent_comment = Comment.objects.get(pk=parent_comment_id)

        response = super().form_valid(form)
        messages.success(self.request, 'Successfully posted new comment!')
        logger.info(f'User {self.request.user} posted a new comment {comment.pk}')
        return response

    def form_invalid(self, form):
        for field, errors in form.errors.items():
            messages.error(self.request, errors)

        post_id = self.kwargs['post_id']
        return redirect('post_detail', post_id)


class DeleteCommentView(LoginRequiredMixin, DeleteView):
    model = Comment
    http_method_names = ['post']

    def get_object(self, queryset=None):
        obj = get_object_or_404(self.model, id=self.kwargs.get('comment_id'))
        if obj.author != self.request.user:
            raise PermissionDenied("You don't have permission to delete this post.")
        return obj

    def form_valid(self, form):
        self.object.is_deleted = True
        self.object.save()
        messages.success(self.request, 'Successfully deleted comment')
        logger.warning(f'User {self.request.user} deleted comment {self.object.pk}')
        return redirect('post_detail', self.object.post.id)


class CommentReactionView(LoginRequiredMixin, View):
    http_method_names = ['post']

    def get_object(self):
        return get_object_or_404(Comment, id=self.kwargs.get('comment_id'))

    # noinspection PyMethodMayBeStatic
    def post(self, request, *args, **kwargs):
        reaction_type = request.POST.get('reaction_type')

        if reaction_type not in ['like', 'dislike']:
            return HttpResponseBadRequest('Invalid request')

        comment = self.get_object()
        with transaction.atomic():

templates/posts/category_create.html
{% extends 'base.html' %}
{% block page_content %}
    <h2 class="mb-4">Create a New Category</h2>
    <form method="post">
        {% csrf_token %}
        {% for field in form %}
            <div class="form-group mb-3{% if field.errors %} has-error{% endif %}">
                {{ field.label_tag }}
                {{ field }}
                {% if field.help_text %}
                    <small class="form-text text-muted">{{ field.help_text }}</small>
                {% endif %}
                {% for error in field.errors %}
                    <div class="alert alert-danger mt-2" role="alert">{{ error }}</div>
                {% endfor %}
            </div>
        {% endfor %}
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
{% endblock %}

templates/posts/category_detail.html
{% extends 'base.html' %}

{% block page_content %}
    <h2 class="display-4">{{ category.title }}</h2>
    <p class="lead">{{ category.description }}</p>

    <div class="row mt-4">
        <!-- Blog posts -->
        <div class="col-md-8">
            {% for post in posts %}
                <div class="card mb-4 border-0 shadow-lg">
                    <div class="card-header bg-secondary text-white d-flex justify-content-between">
                        <span>{{ post.date_published }}</span>
                        <span class="badge bg-dark">Views: {{ post.views }}</span>
                    </div>
                    <div class="card-body">
                        <div class="row">
                            <div class="col-md-6">
                                <h5 class="card-title">
                                    <a href="{% url 'post_detail' post.id %}" class="text-dark text-decoration-none">
                                        {{ post.title }}
                                    </a>
                                </h5>
                                <p class="card-text">Written
                                    by: {{ post.author.first_name }} {{ post.author.last_name }}</p>
                            </div>
                            <div class="col-md-6">
                                <div class="fade-out">
                                    {{ post.content|safe }}
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
    <a href="{% url 'post_list' %}" class="btn btn-primary">All Posts</a>
{% endblock %}

templates/posts/comment_detail.html
{% load static %}

<div>
    <div class="card mt-2" style="margin-left: {{ depth|default:'0' }}px;">
        <div class="card-body comment-container {% if comment.is_deleted %}deleted-comment{% endif %}">
            <div class="comment-flex-container">
                <!-- Profile picture -->
                <img src="
                        {% if comment.author.profile_picture %}{{ comment.author.profile_picture.url }}{% else %}{% static 'images/profile-placeholder.jpg' %}{% endif %}"
                     class="profile-picture" alt="Profile Picture">
                <!-- Grouped content -->
                <div class="comment-content">
                    <strong>{{ comment.author }}</strong>
                    {% if comment.is_profane or comment.is_negative %}
                        <p class="content-placeholder" onclick="toggleCommentContent(this, {{ comment.id }})">
                            THIS COMMENT HAS BEEN MARKED FOR PROFANITY OR NEGATIVITY. CLICK TO REVEAL.
                        </p>
                        <p class="original-content" id="comment-content-{{ comment.id }}" style="display: none;">
                            {{ comment.content }}
                            <button onclick="toggleCommentContent(null, {{ comment.id }})" class="hide-content-btn">
                                Hide
                            </button>

                        </p>
                    {% else %}
                        <p>{{ comment.content }}</p>
                    {% endif %}
                </div>
            </div>

            {% if comment.author == request.user %}
                <form id="delete-comment-form-{{ comment.id }}" action="{% url 'comment_delete' comment.id %}"
                      method="post" style="display: inline;">
                    {% csrf_token %}
                    <input type="hidden" name="next" value="{{ request.path }}">
                    <button type="button" onclick="confirmDeleteComment({{ comment.id }})" class="delete-button"
                            title="Delete comment">x
                    </button>
                </form>
            {% endif %}

            <div class="d-flex align-items-center">
                <!-- Like form -->
                <form action="{% url 'comment_reaction' comment.id %}" method="post" style="display: inline;">
                    {% csrf_token %}
                    <input type="hidden" name="reaction_type" value="like">
                    <button type="submit" class="btn btn-sm btn-outline-primary me-2">
                        <i class="bi bi-thumbs-up"></i> {{ comment.likes_count }} 👍
                    </button>
                </form>

                <!-- Dislike form -->
                <form action="{% url 'comment_reaction' comment.id %}" method="post" style="display: inline;">
                    {% csrf_token %}
                    <input type="hidden" name="reaction_type" value="dislike">
                    <button type="submit" class="btn btn-sm btn-outline-danger me-4">
                        <i class="bi bi-thumbs-down"></i> {{ comment.dislikes_count }} 👎
                    </button>
                </form>

                <small class="text-muted">{{ comment.timestamp|timesince }} ago · {{ comment.timestamp }}</small>
                <button type="button" onclick="setReplyTo('{{ comment.id }}', '{{ comment.content|escapejs }}');"
                        class="btn btn-sm btn-outline-secondary m-auto">Reply
                </button>

            </div>
        </div>
    </div>

    <!-- Recursive inclusion for nested comments -->
    {% with replies=comment.comment_set.all new_depth=depth|add:'20' %}
        {% for reply in replies %}
            {% include 'posts/comment_detail.html' with comment=reply depth=new_depth %}
        {% endfor %}
    {% endwith %}
</div>

templates/posts/create_category.html
{% extends 'base.html' %}
{% block page_content %}
    <h2 class="mb-4">Create a New Category</h2>
    <form method="post">
        {% csrf_token %}
        {% for field in form %}
            <div class="form-group mb-3{% if field.errors %} has-error{% endif %}">
                {{ field.label_tag }}
                {{ field }}
                {% if field.help_text %}
                    <small class="form-text text-muted">{{ field.help_text }}</small>
                {% endif %}
                {% for error in field.errors %}
                    <div class="alert alert-danger mt-2" role="alert">{{ error }}</div>
                {% endfor %}
            </div>
        {% endfor %}
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
{% endblock %}

templates/posts/create_post.html
{% extends 'base.html' %}
{% block page_content %}
    <h2 class="mb-4">Create a New Post</h2>
    <form method="post">
        {% csrf_token %}
        {% for field in form %}
            <div class="form-group mb-3{% if field.errors %} has-error{% endif %}">
                {{ field.label_tag }}

                <!-- Check if current field is category -->
                {% if field.name == 'category' %}
                    <div class="d-flex align-items-center">
                        {{ field }}
                        <a href="{% url 'create_category' %}?next={{ request.path }}" class="btn btn-secondary ml-3">Create
                            a new category</a>
                    </div>
                {% else %}
                    {{ field }}
                {% endif %}

                {% if field.help_text %}
                    <small class="form-text text-muted">{{ field.help_text }}</small>
                {% endif %}
                {% for error in field.errors %}
                    <div class="alert alert-danger mt-2" role="alert">{{ error }}</div>
                {% endfor %}
            </div>
        {% endfor %}
        <div class="form-group mb-3">
            <label for="author">Author:</label>
            <input type="text" id="author" class="form-control" value="{{ request.user }}" readonly>
            <small class="form-text text-muted">This field is autofilled and read-only.</small>
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
{% endblock %}

templates/posts/post_detail.html
{% extends 'base.html' %}

{% load static %}

{% block extra_head %}
    <script src="https://kit.fontawesome.com/53cf010cf5.js" crossorigin="anonymous"></script>
{% endblock %}


{% block styles %}
    <style>
        .errorlist {
            margin: 0;
            padding: 0;
            list-style-type: none;
        }

        .btn-facebook {
            background-color: #3b5998;
            color: white;
        }

        .btn-twitter {
            background-color: #1da1f2;
            color: white;
        }

        .btn-linkedin {
            background-color: #0077b5;
            color: white;
        }

        .btn-pinterest {
            background-color: #bd081c;
            color: white;
        }

        .btn-email {
            background-color: #333333;
            color: white;
        }

        .btn-facebook:hover, .btn-twitter:hover, .btn-linkedin:hover, .btn-pinterest:hover, .btn-email:hover {
            opacity: 0.8;
        }

    </style>
{% endblock %}

{% block page_content %}
    {% if messages %}
        <div class="mt-4">
            {% for message in messages %}
                <div class="alert {% if message.tags %}alert-{{ message.tags }}{% endif %} mb-0" role="alert">
                    {{ message }}
                </div>
            {% endfor %}
        </div>
    {% endif %}

    <div class="d-flex justify-content-between align-items-center mt-4">
        <a href="{% url 'post_list' %}" class="btn btn-primary">All Posts</a>
        {% if request.user == post.author %}
            <form id="delete-post-form" method="post" action="{% url 'delete_post' post.id %}" style="display: none;">
                {% csrf_token %}
            </form>
            <div>
                <a href="{% url 'edit_post' post.id %}" class="btn btn-warning">Edit Post</a>
                <button onclick="confirmDeletePost()" class="btn btn-danger">Delete Post</button>
            </div>
        {% endif %}
    </div>

    <div class="card border-0 shadow my-4">
        <div class="card-body">
            <h1 class="card-title">{{ post.title }}</h1>
            <p class="card-subtitle mb-2 text-muted">
                Created: {{ post.date_published }} |
                Views: {{ post.views }} |
                Author: {{ post.author.first_name }} {{ post.author.last_name }}
            </p>
            <hr class="my-4"/>
            <div class="card-text mb-4">
                {{ post.content|safe }}
            </div>
            <hr class="my-4"/>
            <p>Category: {{ post.category.title }}</p>

            <div>
                <button onclick="sharePost({{ post.id }}); copyToClipboard('{{ request.build_absolute_uri }}')"
                        class="btn btn-secondary">Copy Link
                </button>
                <a href="https://www.facebook.com/sharer/sharer.php?u={{ request.build_absolute_uri|urlencode }}"
                   target="_blank" onclick="sharePost({{ post.id }})" class="btn btn-facebook">
                    <i class="fab fa-facebook-f"></i> Share on Facebook
                </a>

                <a href="https://twitter.com/intent/tweet?text={{ post.title|urlencode }}&url={{ request.build_absolute_uri|urlencode }}"
                   target="_blank" onclick="sharePost({{ post.id }})" class="btn btn-twitter">
                    <i class="fab fa-twitter"></i> Share on Twitter
                </a>
                <a href="https://www.linkedin.com/shareArticle?mini=true&url={{ request.build_absolute_uri|urlencode }}&title={{ post.title|truncatechars:200|urlencode }}&summary={{ post.content|truncatewords:20|striptags|urlencode }}"
                   target="_blank" onclick="sharePost({{ post.id }})" class="btn btn-linkedin">
                    <i class="fab fa-linkedin-in"></i> Share on LinkedIn
                </a>
                <a href="https://pinterest.com/pin/create/button/?url={{ request.build_absolute_uri|urlencode }}&media={% static 'images/favicon.png' %}&description={{ post.title|urlencode }}"
                   target="_blank" onclick="sharePost({{ post.id }})" class="btn btn-pinterest">
                    <i class="fab fa-pinterest-p"></i> Share on Pinterest
                </a>
                <a href="mailto:?subject={{ post.title|urlencode }}&body=Check out this post: {{ request.build_absolute_uri|urlencode }}"
                   onclick="sharePost({{ post.id }})" class="btn btn-email">
                    <i class="fas fa-envelope"></i> Share via Email
                </a>
            </div>

        </div>
    </div>
    {% include 'posts/comment_list.html' %}

    <script type="text/javascript">
        function confirmDeletePost() {
            if (confirm('Are you sure you want to delete this post?')) {
                // If the user confirms, submit the hidden form
                document.getElementById('delete-post-form').submit();
            }
        }

        function confirmDeleteComment(commentId) {
            if (confirm('Are you sure you want to delete this comment?')) {
                document.getElementById('delete-comment-form-' + commentId).submit();
            }
        }

        function copyToClipboard(text) {
            navigator.clipboard.writeText(text).then(() => {
                alert('Link copied to clipboard');
            }).catch(err => {
                console.error('Error in copying text: ', err);
            });
        }

        function sharePost(postId) {
            fetch("{% url 'share_post' %}", {
                method: 'POST',
                headers: {
                    'Content-Type': 'application/json',
                    'X-CSRFToken': getCookie('csrftoken')
                },
                body: JSON.stringify({post_id: postId})
            })
                .then(response => response.json())
                .catch(error => console.error('Error:', error));
        }
    </script>
{% endblock %}